import type { Metadata } from "next";
import { Inter, Fira_Mono, Onest } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import "highlight.js/styles/github.css"
import { onest } from "@/lib/fontsConfig";

// export const inter = Inter({ subsets: ["latin"] });
// export const firaMono = Fira_Mono({subsets: ["latin"], weight: "500"})
// export const onest = Onest({subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={onest.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
